/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A: typeof import('./components/A.vue')['default']
    B: typeof import('./components/B.vue')['default']
    Ddd: typeof import('./components/Ddd.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Page1: typeof import('./view/oneOne/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/common/Basic/SvgIcon.vue')['default']
    WBack: typeof import('./components/common/Navigation/w-Back.vue')['default']
    WBreadcrumb: typeof import('./components/common/Navigation/w-Breadcrumb.vue')['default']
    WButtons: typeof import('./components/common/Basic/w-Buttons.vue')['default']
    WDescriptions: typeof import('./components/common/Data/w-Descriptions.vue')['default']
    WDialog: typeof import('./components/common/Feedback/w-Dialog.vue')['default']
    WDrawer: typeof import('./components/common/Feedback/w-Drawer.vue')['default']
    WForms: typeof import('./components/common/Form/w-Forms.vue')['default']
    WMenu: typeof import('./components/common/Navigation/w-Menu.vue')['default']
    WNavigation: typeof import('./components/common/Navigation/w-Navigation.vue')['default']
    WPagination: typeof import('./components/common/Data/w-Pagination.vue')['default']
    WTable: typeof import('./components/common/Data/w-Table.vue')['default']
    WTabs: typeof import('./components/common/Navigation/w-Tabs.vue')['default']
    WTexts: typeof import('./components/common/Form/w-Texts.vue')['default']
    WTitles: typeof import('./components/common/Basic/w-Titles.vue')['default']
    WUpload: typeof import('./components/common/Form/w-Upload.vue')['default']
  }
}
